import { Injectable, Logger } from '@nestjs/common';
import {
  IIntegrationAdapter,
  HealthCheckResult,
  IntegrationResource,
  GrantAccessInput,
  GrantAccessResult,
  RevokeAccessInput,
} from '../core/integration-adapter.interface';
import { IntegrationProvider } from '../core/integration-types';
import { IntegrationEncryptionService } from '../core/integration-encryption.service';
import { PrismaService } from '../../prisma/prisma.service';
import { ConfigService } from '@nestjs/config';

/**
 * GmailAdapter
 *
 * Handles the complete Gmail OAuth 2.0 lifecycle:
 *  - Authorization URL generation (for the web dashboard to redirect to)
 *  - OAuth code exchange (callback handler)
 *  - Access token refresh (lazy, on-demand)
 *  - Token storage via IntegrationEncryptionService (reuses IntegrationConnection)
 *  - Health check via Gmail profile endpoint
 *
 * OAuth Boundary Rule:
 *   ALL Google OAuth and Gmail API interactions are confined to this class.
 *   No other module may import OAuth helpers, refresh tokens, or call Gmail API.
 *   All calls use native fetch() — no googleapis SDK.
 *
 * NOTE: grantAccess / revokeAccess are not applicable to Gmail.
 * Gmail is used by the grantor to receive OTPs; it is not a delegation target.
 */
@Injectable()
export class GmailAdapter implements IIntegrationAdapter {
  readonly provider = 'GMAIL' as IntegrationProvider;
  private readonly logger = new Logger(GmailAdapter.name);

  private readonly TOKEN_URL = 'https://oauth2.googleapis.com/token';
  private readonly PROFILE_URL = 'https://gmail.googleapis.com/gmail/v1/users/me/profile';
  private readonly AUTH_URL = 'https://accounts.google.com/o/oauth2/v2/auth';

  constructor(
    private readonly encryption: IntegrationEncryptionService,
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {}

  // ─── OAuth Flow ─────────────────────────────────────────────────────────────

  /**
   * Generates the Google OAuth authorization URL.
   * The web dashboard redirects the user here to begin the OAuth consent flow.
   *
   * @param state  CSRF token generated by the caller, stored in session, verified on callback.
   */
  buildAuthorizationUrl(state: string): string {
    const params = new URLSearchParams({
      client_id: this.config.getOrThrow('GOOGLE_CLIENT_ID'),
      redirect_uri: this.config.getOrThrow('GOOGLE_REDIRECT_URI'),
      response_type: 'code',
      // Minimum scope: read-only access to Gmail for OTP retrieval
      scope: 'https://www.googleapis.com/auth/gmail.readonly',
      access_type: 'offline',   // Required to receive a refresh_token
      prompt: 'consent',        // Forces consent screen so refresh_token is always issued
      state,
    });
    return `${this.AUTH_URL}?${params.toString()}`;
  }

  /**
   * Exchanges the OAuth authorization code (from callback) for access + refresh tokens.
   * Encrypts both tokens and stores them in IntegrationConnection.
   *
   * @param organizationId  The organization connecting Gmail
   * @param userId          The user performing the connection
   * @param code            The authorization code from Google callback
   */
  async exchangeCodeAndStore(
    organizationId: string,
    userId: string,
    code: string,
  ): Promise<{ grantedEmail: string }> {
    // ── Exchange code for tokens ────────────────────────────────────────────
    const tokenRes = await fetch(this.TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        code,
        client_id: this.config.getOrThrow('GOOGLE_CLIENT_ID'),
        client_secret: this.config.getOrThrow('GOOGLE_CLIENT_SECRET'),
        redirect_uri: this.config.getOrThrow('GOOGLE_REDIRECT_URI'),
        grant_type: 'authorization_code',
      }).toString(),
    });

    if (!tokenRes.ok) {
      const err = await tokenRes.text().catch(() => '');
      throw new Error(`Google token exchange failed: ${tokenRes.status} ${err.slice(0, 200)}`);
    }

    const tokens = await tokenRes.json() as any;
    const { access_token, refresh_token, expires_in } = tokens;

    if (!access_token || !refresh_token) {
      throw new Error('Google did not return a refresh token. Re-authorization required.');
    }

    // ── Resolve the Gmail address that was authorized ───────────────────────
    const profileRes = await fetch(this.PROFILE_URL, {
      headers: { Authorization: `Bearer ${access_token}` },
    });
    if (!profileRes.ok) {
      throw new Error('Failed to resolve Gmail address after token exchange.');
    }
    const profile = await profileRes.json() as any;
    const grantedEmail: string = profile.emailAddress;

    // ── Encrypt access token (stored as encryptedToken) ─────────────────────
    const { encryptedToken, encryptedDek, keyMetadataId } =
      await this.encryption.encryptToken(access_token, organizationId, 'GMAIL');

    // ── Encrypt refresh token (stored separately in providerMeta) ───────────
    const { encryptedToken: encryptedRefreshToken } =
      await this.encryption.encryptToken(refresh_token, organizationId, 'GMAIL_REFRESH');

    const tokenExpiry = Date.now() + (expires_in ?? 3600) * 1000;

    // ── Upsert IntegrationConnection ─────────────────────────────────────────
    await this.prisma.integrationConnection.upsert({
      where: { organizationId_provider: { organizationId, provider: 'GMAIL' as IntegrationProvider } },
      update: {
        status: 'ACTIVE',
        encryptedToken,
        encryptedDek,
        keyMetadataId,
        providerMeta: {
          encryptedRefreshToken,  // AES-256-GCM encrypted
          tokenExpiry,
          scope: 'gmail.readonly',
          grantedEmail,
        } as any,
        lastCheckedAt: new Date(),
        lastError: null,
        updatedBy: userId,
        deletedAt: null,
      },
      create: {
        organizationId,
        provider: 'GMAIL' as IntegrationProvider,
        status: 'ACTIVE',
        encryptedToken,
        encryptedDek,
        keyMetadataId,
        providerMeta: {
          encryptedRefreshToken,
          tokenExpiry,
          scope: 'gmail.readonly',
          grantedEmail,
        } as any,
        lastCheckedAt: new Date(),
        createdBy: userId,
        updatedBy: userId,
      },
    });

    this.logger.log(`[GMAIL] Connected for org ${organizationId} (email: ${grantedEmail})`);
    return { grantedEmail };
  }

  /**
   * Returns a valid (possibly refreshed) access token for the grantor's Gmail.
   * Performs a lazy token refresh if the stored token has expired.
   *
   * @param organizationId  The grantor's organization ID
   */
  async getValidAccessToken(organizationId: string): Promise<string> {
    const conn = await this.prisma.integrationConnection.findFirst({
      where: { organizationId, provider: 'GMAIL' as IntegrationProvider, deletedAt: null, status: 'ACTIVE' },
    });

    if (!conn) {
      throw new Error('Gmail is not connected for this organization.');
    }

    const meta = (conn.providerMeta ?? {}) as Record<string, any>;
    const tokenExpiry: number = meta.tokenExpiry ?? 0;

    // Token still valid — return it directly
    if (tokenExpiry > Date.now() + 60_000) {
      return this.encryption.decryptToken(conn.encryptedToken, conn.encryptedDek, organizationId, 'GMAIL');
    }

    // ── Lazy refresh ─────────────────────────────────────────────────────────
    this.logger.debug(`[GMAIL] Access token expired for org ${organizationId}, refreshing...`);

    const encryptedRefreshToken: string = meta.encryptedRefreshToken;
    if (!encryptedRefreshToken) {
      await this.markError(conn.id, 'Refresh token missing — re-authorization required.');
      throw new Error('Gmail refresh token is missing. Please reconnect Gmail.');
    }

    const refreshToken = this.encryption.decryptToken(
      encryptedRefreshToken,
      conn.encryptedDek,
      organizationId,
      'GMAIL_REFRESH',
    );

    const tokenRes = await fetch(this.TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'refresh_token',
        refresh_token: refreshToken,
        client_id: this.config.getOrThrow('GOOGLE_CLIENT_ID'),
        client_secret: this.config.getOrThrow('GOOGLE_CLIENT_SECRET'),
      }).toString(),
    });

    if (!tokenRes.ok) {
      const err = await tokenRes.text().catch(() => '');
      await this.markError(conn.id, `Token refresh failed: ${tokenRes.status}`);
      throw new Error(`Gmail token refresh failed (${tokenRes.status}): ${err.slice(0, 200)}`);
    }

    const newTokens = await tokenRes.json() as any;
    const { access_token: newAccessToken, expires_in } = newTokens;

    if (!newAccessToken) {
      await this.markError(conn.id, 'Refresh response missing access_token');
      throw new Error('Gmail token refresh returned no access token.');
    }

    // Encrypt and persist the new access token
    const { encryptedToken, encryptedDek, keyMetadataId } =
      await this.encryption.encryptToken(newAccessToken, organizationId, 'GMAIL');

    await this.prisma.integrationConnection.update({
      where: { id: conn.id },
      data: {
        encryptedToken,
        encryptedDek,
        keyMetadataId,
        providerMeta: {
          ...meta,
          tokenExpiry: Date.now() + (expires_in ?? 3600) * 1000,
        } as any,
        status: 'ACTIVE',
        lastError: null,
        lastCheckedAt: new Date(),
      },
    });

    this.logger.log(`[GMAIL] Token refreshed for org ${organizationId}`);
    return newAccessToken;
  }

  // ─── IIntegrationAdapter: validateToken ─────────────────────────────────────

  async validateToken(token: string): Promise<{ identity: string; meta?: Record<string, unknown> }> {
    const res = await fetch(this.PROFILE_URL, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!res.ok) throw new Error(`Gmail token validation failed: ${res.status}`);
    const profile = await res.json() as any;
    return {
      identity: profile.emailAddress,
      meta: { messagesTotal: profile.messagesTotal, threadsTotal: profile.threadsTotal },
    };
  }

  // ─── IIntegrationAdapter: healthCheck ───────────────────────────────────────

  async healthCheck(token: string): Promise<HealthCheckResult> {
    const checkedAt = new Date();
    try {
      const { identity } = await this.validateToken(token);
      return { healthy: true, identity: `Gmail connected as ${identity}`, checkedAt };
    } catch (err: unknown) {
      return { healthy: false, error: (err as Error).message, checkedAt };
    }
  }

  // ─── IIntegrationAdapter: listResources ─────────────────────────────────────

  async listResources(_token: string): Promise<IntegrationResource[]> {
    // Gmail is a single-mailbox connection; it doesn't model "resources" in the
    // sense of teams or repos. Return the inbox as a single logical resource.
    return [{ id: 'inbox', name: 'Gmail Inbox', type: 'ACCOUNT' }];
  }

  // ─── IIntegrationAdapter: grantAccess / revokeAccess (Not Applicable) ───────

  async grantAccess(_token: string, _input: GrantAccessInput): Promise<GrantAccessResult> {
    throw new Error(
      'Gmail does not support programmatic access delegation. ' +
      'Gmail is used by the grantor to receive OTPs for delegated sessions.',
    );
  }

  async revokeAccess(_token: string, _input: RevokeAccessInput): Promise<void> {
    throw new Error(
      'Gmail access cannot be revoked via this API. ' +
      'Disconnect the Gmail integration from the dashboard instead.',
    );
  }

  // ─── Internal helpers ────────────────────────────────────────────────────────

  private async markError(connectionId: string, error: string): Promise<void> {
    await this.prisma.integrationConnection
      .update({ where: { id: connectionId }, data: { status: 'ERROR', lastError: error } })
      .catch(() => {});
  }
}
