/**
 * Type aliases for IntegrationProvider and IntegrationStatus enums.
 * These will be generated by Prisma once the migration runs.
 * Using string-literal unions here keeps TypeScript happy without requiring the migration to have run.
 */
export type IntegrationProvider = 'VERCEL' | 'GITHUB' | 'GODADDY' | 'GMAIL';
export const IntegrationProvider = {
  VERCEL: 'VERCEL' as IntegrationProvider,
  GITHUB: 'GITHUB' as IntegrationProvider,
  GODADDY: 'GODADDY' as IntegrationProvider,
  GMAIL: 'GMAIL' as IntegrationProvider,
};

export type IntegrationStatus = 'ACTIVE' | 'DISCONNECTED' | 'ERROR';
export const IntegrationStatus = {
  ACTIVE: 'ACTIVE' as IntegrationStatus,
  DISCONNECTED: 'DISCONNECTED' as IntegrationStatus,
  ERROR: 'ERROR' as IntegrationStatus,
};
