name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npm run db:generate
      
    - name: Lint
      run: npm run lint
      
    - name: Typecheck API
      run: npm run check-types --workspace=api

    - name: Typecheck Web
      run: npm run check-types --workspace=web
      
    - name: Run Tests
      run: npm run test
      
    - name: Build API
      run: npm run build --workspace=api
      
    - name: Build Web
      run: npm run build --workspace=web
